import { NavigationMap } from "../types"

export const virex9Map: NavigationMap = {
  id: "virex-9",
  name: "Virex-9",
  description: "Known navigable locations within Virex-9.",

background: "/static/maps/virex9.webp",

  locations: [
    {
      id: "iron-halo",
      name: "Iron Halo",
      description: "Neutral territory and known contact point.",
      x: 24,
      y: 35,
      discovered: true,
      status: "available",
      icon: "city",
    },
    {
      id: "coil-market",
      name: "Coil Market",
      description: "Multi-level trade district surrounding the gravity coil.",
      x: 62,
      y: 48,
      discovered: true,
      status: "available",
      icon: "market",
    },
    {
      id: "skybridge-04",
      name: "Skybridge 04",
      description: "Elevated transit structure between upper city sectors.",
      x: 44,
      y: 22,
      discovered: true,
      status: "available",
      icon: "bridge",
    },
    {
      id: "docking-spires",
      name: "Docking Spires",
      description: "Primary arrival and departure infrastructure.",
      x: 78,
      y: 68,
      discovered: true,
      status: "available",
      icon: "dock",
    },
    {
      id: "reactor-13",
      name: "Reactor Sector 13",
      description: "Restricted reactor complex.",
      x: 58,
      y: 58,
      discovered: false,
      status: "restricted",
      icon: "reactor",
    },
    {
      id: "scarline-eco-station",
      name: "Scarline Eco-Station",
      description: "Environmental research and reclamation facility.",
      x: 15,
      y: 74,
      discovered: false,
      status: "offline",
      icon: "station",
    },
  ],
}