import { NavigationMap } from "../types"

export const virex9Map: NavigationMap = {
  id: "virex-9",
  name: "Virex-9",
  description: "Known navigable locations within Virex-9.",

background: "/static/maps/virex9.webp",

  locations: [
    {
      id: "iron-halo",
      name: "Iron Halo",
      description: "Neutral territory and known contact point.",
      x: 78,
      y: 72,
      discovered: true,
      status: "available",
      icon: "city",
    },
    {
      id: "coil-market",
      name: "Coil Market",
      description: "Multi-level trade district surrounding the gravity coil.",
      x: 51,
      y: 49,
      discovered: true,
      status: "available",
      icon: "market",
    },
    {
      id: "skybridge-04",
      name: "Skybridge 04",
      description: "Elevated transit structure between upper city sectors.",
      x: 49,
      y: 32,
      discovered: true,
      status: "available",
      icon: "bridge",
    },
    {
      id: "docking-spires",
      name: "Docking Spires",
      description: "Primary arrival and departure infrastructure.",
      x: 22,
      y: 66,
      discovered: true,
      status: "available",
      icon: "dock",
    },
    {
      id: "reactor-13",
      name: "Reactor Sector 13",
      description: "Restricted reactor complex.",
      x: 59,
      y: 38,
      discovered: true,
      status: "restricted",
      icon: "reactor",
    },
    {
      id: "scarline-City-station",
      name: "Scarline City-Station",
      description: "transport medium.",
      x: 71,
      y: 44,
      discovered: true,
      status: "offline",
      icon: "station",
    },
        {
      id: "rust-bucket-cache",
      name: "Rust Bucket`s cache",
      description: "Last known position for a cache of 'borrowed' goods.",
      x: 66,
      y: 85,
      discovered: true,
      status: "offline",
      icon: "station",
    },
  ],
}
